$DebugPreference = 'Continue'
$gitRoot = git rev-parse --show-toplevel

function Get-ComponentVersion {
    param (
        [string]$componentName
    )
    $version = Get-Content "$gitRoot/deploy/versions/$componentName.version"
    Write-Debug "$($componentName): $version"

    return $version
}

function Set-Chart {
    param (
        [string]$chartPath,
        [array]$components
    )
    $now = [datetime]::Now
    $message = "#### AUTOGENERATED ($now) DO NOT EDIT BY HAND #####"
    
    $chartContent = Get-Content "$gitRoot/$chartPath/Chart.template.yaml"
    $chartContent = $chartContent.Replace('{Message}',$message)

    foreach ($component in $components) {
        $component_version = Get-ComponentVersion $component
        
        $chartContent = $chartContent.Replace("{$($component).version}",$component_version)
    }
    $chartContent

    Set-Content -Value $chartContent -Path "$gitRoot/$chartPath/Chart.yaml"
}