apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ll-app
  namespace: argocd
spec:
  destination:
    namespace: ll
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
  source:
    repoURL: {{ .Values.argocd.repoURL }}
    targetRevision: 0.1.*
    chart: helm/ll-app
    helm:
      values: |
        #
        environmentHost: dev.legends-legacy.com

        ll-frontend:
          env:
            environment:
              value: "dev"
            allowAnonymous:
              value: "true"
            isLocal:
              value: "false"
            chatApiRoot:
              value: "chat"
            googleClientId:
              value: "431775673466-bq6f5ucno6j985rbstvf8b5aliqvo6h1.apps.googleusercontent.com"

        ll-backend:
          env:
            ASPNETCORE_ENVIRONMENT:
              value: Development

            ConnectionStrings__LegendsLegacyDB:
              valueFrom:
                secretKeyRef:
                  name: postgres-ll-connection
                  key: connectionString
            
            Google__ClientId:
              value: "431775673466-bq6f5ucno6j985rbstvf8b5aliqvo6h1.apps.googleusercontent.com"

            FeatureManagement__AllowAnonymous:
              value: true

            FeatureManagement__DisableAllRequests:
              values: true

        ll-chat:
          env:
            ASPNETCORE_ENVIRONMENT:
              value: Development

            ConnectionStrings__LLChatDB:
              valueFrom:
                secretKeyRef:
                  name: postgres-chat-connection
                  key: connectionString
