apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ll-app
  namespace: argocd
spec:
  destination:
    namespace: ll
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
  source:
    repoURL: {{ .Values.argocd.repoURL }}
    targetRevision: 0.1.*
    chart: helm/ll-app
    helm:
      values: |
        #
        environmentHost: dev.legends-legacy.com

        ll-frontend:
          env:
            environment:
              value: "dev"
            allowAnonymous:
              value: "true"
            isLocal:
              value: "false"
            chatApiRoot:
              value: "chat"

        ll-backend:
          env:
            ASPNETCORE_ENVIRONMENT:
              value: Development

            ConnectionStrings__LegendsLegacyDB:
              valueFrom:
                secretKeyRef:
                  name: postgres-game-connection
                  key: connectionString

            FeatureManagement__AllowAnonymous:
              value: "true"

        ll-chat:
          env:
            ASPNETCORE_ENVIRONMENT:
              value: Development

            ConnectionStrings__LLChatDB:
              valueFrom:
                secretKeyRef:
                  name: postgres-chat-connection
                  key: connectionString
