apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-sql-edge-deployment
  namespace: mssql
spec:
  selector:
    matchLabels:
      app: mssql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
      - name: mssql
        image: mcr.microsoft.com/azure-sql-edge:latest
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql-secret
              key: password
        volumeMounts:
        - name: mssql-persistent-storage
          mountPath: /var/opt/mssql
        securityContext:
          runAsUser: 10001   # Default MSSQL non-root user
          runAsGroup: 0       # MSSQL group
          fsGroup: 10001      # Ensures that the `mssql` user has access to mounted volumes
      volumes:
      - name: mssql-persistent-storage
        persistentVolumeClaim:
          claimName: mssql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-service
  namespace: mssql
spec:
  type: NodePort
  ports:
  - port: 1433
    targetPort: 1433
    nodePort: 30000 # Choose a NodePort between 30000-32767
  selector:
    app: mssql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-pv-claim
  namespace: mssql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
