apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgadmin-secret
              key: password
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: pgadmin-secret
              key: username
        - name: POSTGRES_DB
          value: mydatabase
        resources:
          requests:
            memory: "2Gi"
          limits:
            memory: "3Gi"
        volumeMounts:
        - name: postgresql-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgresql-data
        persistentVolumeClaim:
          claimName: postgresql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  namespace: database
spec:
  type: NodePort
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 30001
  selector:
    app: postgresql
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv
  namespace: database
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/postgresql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
  namespace: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi