apiVersion: v1
kind: Secret
metadata:
  name: postgres-ll-connection
  namespace: ll
type: Opaque
stringData:
  connectionString: "Host=postgres-ll;Port=5432;Database=legends_legacy;Username=ll_user;Password=sup3rSecr3t;Pooling=true;Ssl Mode=Disable"

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-ll
  namespace: ll
labels:
  app: postgres-ll
spec:
  clusterIP: None
  ports:
  - port: 5432
    name: postgres
  selector:
    app: postgres-ll

---

apiVersion: v1
kind: Secret
metadata:
  name: postgres-ll-credentials
  namespace: ll
type: Opaque
stringData:
  POSTGRES_USER: ll_user
  POSTGRES_PASSWORD: sup3rSecr3t
  POSTGRES_DB: legends_legacy
  connectionString: |
    Host=postgres-ll;Port=5432;Database=legends_legacy;Username=ll_user;Password=sup3rSecr3t;Pooling=true;Ssl Mode=Disable

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-ll
  namespace: ll
spec:
  serviceName: postgres-ll
  replicas: 1
  selector:
    matchLabels:
      app: postgres-ll
  template:
    metadata:
      labels:
        app: postgres-ll
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        ports:
        - containerPort: 5432
        envFrom:
          - secretRef:
              name: postgres-chat-credentials
        env:
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: local-path
      resources:
        requests:
          storage: 8Gi
