apiVersion: v1
kind: Secret
metadata:
  name: postgres-chat-connection
  namespace: ll
type: Opaque
stringData:
  connectionString: "Host=postgres-chat;Port=5432;Database=ll_chat;Username=chat_user;Password=an0th3rSecr3t;Pooling=true;Ssl Mode=Disable"

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-chat
  namespace: ll
labels:
  app: postgres-chat
spec:
  clusterIP: None
  ports:
  - port: 5432
    name: postgres
  selector:
    app: postgres-chat

---

apiVersion: v1
kind: Secret
metadata:
  name: postgres-chat-credentials
  namespace: ll
type: Opaque
stringData:
  POSTGRES_USER: chat_user
  POSTGRES_PASSWORD: an0th3rSecr3t
  POSTGRES_DB: ll_chat
  connectionString: |
    Host=postgres-chat;Port=5432;Database=ll_chat;Username=chat_user;Password=an0th3rSecr3t;Pooling=true;Ssl Mode=Disable

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-chat
  namespace: ll
spec:
  serviceName: postgres-chat
  replicas: 1
  selector:
    matchLabels:
      app: postgres-chat
  template:
    metadata:
      labels:
        app: postgres-chat
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        ports:
        - containerPort: 5432
        envFrom:
          - secretRef:
              name: postgres-chat-credentials
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: gp2
      resources:
        requests:
          storage: 8Gi