apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seq
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: https://helm.datalust.co
    targetRevision: '*'
    chart: seq
    helm:
      values: |
        #
        ui:
          containerPort: 80
          service:
            port: 8341
          ingress:
            enabled: false
            path: /
            hosts: []
        gelf:
          enabled: true

        service:
          type: LoadBalancer


  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true