name: Build ll-app

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - "releases/**"
    paths:
      - deploy/ll/ll-app
      - deploy/versions/ll-backend.version
      - deploy/versions/ll-frontend.version

env:
  major: 0
  minor: 0

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_version.outputs.version }}
      tag: ${{ steps.set_tag.outputs.tag }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Latest Patch Version
        id: set_version
        shell: bash
        run: |
          # Fetch all tags to ensure we have the latest
          git fetch --tags

          # Find the latest tag matching the major.minor.* pattern
          LATEST_TAG=$(git tag --list "${{ env.major }}.${{ env.minor }}.*" --sort=-v:refname | head -n1)

          if [ -z "$LATEST_TAG" ]; then
            PATCH=0
          else
            # Extract the patch number and increment it
            PATCH=$(echo "$LATEST_TAG" | awk -F. '{print $3}')
            PATCH=$((PATCH+1))
          fi

          # Output the new version
          VERSION="${{ env.major }}.${{ env.minor }}.$PATCH"
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Determine Tag Based on Branch
        id: set_tag
        shell: bash
        run: |
          VERSION="${{ env.version }}"
          BRANCH="${{ github.ref }}"

          if [[ "$BRANCH" == "refs/heads/main" ]]; then
            TAG="main-$VERSION"
          elif [[ "$BRANCH" == refs/heads/release/* ]]; then
            TAG="release-$VERSION"
          else
            TAG="$VERSION"
          fi

          echo "tag=$TAG" >> $GITHUB_OUTPUT

  generate_chart:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate Chart
        shell: pwsh
        working-directory: "deploy"
        run: |
          . .\generate.chart.ps1
          Set-Chart -chartPath 'deploy/ll/ll-app' -components 'll-frontend', 'll-backend'
      - name: ls
        shell: bash
        run: |
          ls deploy/ll/ll-app
      - name: cat
        shell: bash
        run: |
          cat deploy/ll/ll-app/Chart.yaml
  helm:
    needs:
      - setup
      - generate_chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Helm Package and Push
        uses: ./.github/actions/build-and-push-helm
        with:
          version: ${{ needs.setup.outputs.version }}
          tag: ${{ needs.setup.outputs.tag }}
          workingDirectory: "deploy/ll/ll-app"
          token: ${{ secrets.GITHUB_TOKEN }}
          imageName: "ll-app"
