name: Build ll-app

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - "releases/**"
    paths:
      - deploy/ll/ll-app
      - deploy/versions/ll-backend.version
      - deploy/versions/ll-chat.version
      - deploy/versions/ll-frontend.version

env:
  major: 0
  minor: 0

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_version.outputs.version }}
      tag: ${{ steps.set_tag.outputs.tag }}

    steps:
      - uses: actions/checkout@v4

      - name: Create version variable
        id: set_version
        shell: bash
        run: |
          # Read the version from the file
          version=$(cat versions/ll-app.version)
          echo "Current version is $version"

          # Split the version into major, minor, and patch
          IFS='.' read -r major minor patch <<< "$version"

          # Increment the patch number
          patch=$((patch + 1))

          # Construct the new version
          new_version="${major}.${minor}.${patch}"
          echo "New version is $new_version"

          # Set the version as an output and environment variable
          echo "version=$new_version" >> $GITHUB_OUTPUT
          echo "version=$new_version" >> $GITHUB_ENV

      - name: Set tag variable
        id: set_tag
        shell: bash
        run: |
          echo "GITHUB_REF is $GITHUB_REF"
          version="${{ steps.set_version.outputs.version }}"
          if [[ "$GITHUB_REF" == "refs/heads/main" ]]; then
            tag="main-${version}"
          elif [[ "$GITHUB_REF" == refs/heads/releases/* ]]; then
            tag="release-${version}"
          else
            tag="${version}"
          fi
          echo "Tag is $tag"
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Set tagid and tagcommit
        id: set_tagid
        run: |
          echo "tagid=build-${{ github.run_id }}" >> $GITHUB_OUTPUT
          echo "tagcommit=commit-${{ github.sha }}" >> $GITHUB_OUTPUT

  generate_chart:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate Chart
        shell: pwsh
        working-directory: "deploy"
        run: |
          . .\generate.chart.ps1
          Set-Chart -chartPath 'deploy/ll/ll-app' -components 'll-frontend', 'll-backend', 'll-chat'
      - name: Upload Helm Chart as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: helm-chart
          path: deploy/ll/ll-app
  helm:
    needs:
      - setup
      - generate_chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Helm Chart Artifact
        uses: actions/download-artifact@v4
        with:
          name: helm-chart
          path: deploy/ll/ll-app
      - name: Helm Package and Push
        uses: ./.github/actions/build-and-push-helm
        with:
          version: ${{ needs.setup.outputs.version }}
          tag: ${{ needs.setup.outputs.tag }}
          workingDirectory: "deploy/ll/ll-app"
          token: ${{ secrets.PAT_TOKEN }}
          imageName: "ll-app"

  bump_version:
    runs-on: ubuntu-latest
    needs:
      - setup
      - helm
    steps:
      - uses: actions/checkout@v4
      - name: Update version file
        shell: bash
        run: |
          # Update the version in the file
          echo "${{ needs.setup.outputs.version }}" > versions/ll-app.version
          # Commit and push changes
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add versions/ll-app.version
          git commit -m "Bump ll-app version to ${{ needs.setup.outputs.version }}"
          git push
