name: Build ll-app for dev

on:
  push:
    branches:
      - main
      - "releases/**"
    paths:
      - environments/dev

env:
  major: 0
  minor: 0

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_version.outputs.version }}
      tag: ${{ steps.set_tag.outputs.tag }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Latest Patch Version
        id: set_version
        shell: bash
        run: |
          # Fetch all tags to ensure we have the latest
          git fetch --tags

          # Find the latest tag matching the major.minor.* pattern
          LATEST_TAG=$(git tag --list "${{ env.major }}.${{ env.minor }}.*" --sort=-v:refname | head -n1)

          if [ -z "$LATEST_TAG" ]; then
            PATCH=0
          else
            # Extract the patch number and increment it
            PATCH=$(echo "$LATEST_TAG" | awk -F. '{print $3}')
            PATCH=$((PATCH+1))
          fi

          # Output the new version
          VERSION="${{ env.major }}.${{ env.minor }}.$PATCH"
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Determine Tag Based on Branch
        id: set_tag
        shell: bash
        run: |
          VERSION="${{ env.version }}"
          BRANCH="${{ github.ref }}"

          if [[ "$BRANCH" == "refs/heads/main" ]]; then
            TAG="main-$VERSION"
          elif [[ "$BRANCH" == refs/heads/release/* ]]; then
            TAG="release-$VERSION"
          else
            TAG="$VERSION"
          fi

          echo "tag=$TAG" >> $GITHUB_OUTPUT

  helm:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Helm Package and Push
        uses: ./.github/actions/build-and-push-helm
        with:
          version: ${{ needs.setup.outputs.version }}
          tag: ${{ needs.setup.outputs.tag }}
          workingDirectory: "environments/dev"
          token: ${{ secrets.GITHUB_TOKEN }}
          imageName: "ll-platform-dev"
